import { useEffect, useMemo, useState } from 'react';

const slug = import.meta.env.VITE_VENUE_SLUG || 'casa-aurora';
const money = (minor = 0) => new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN', minimumFractionDigits: 2 }).format(Number(minor || 0) / 100).replace('PEN', 'S/');
const config = window.__ROS_CONFIG__ || {};
const directEnabled = /^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(String(config.supabaseUrl || '')) && String(config.supabaseAnonKey || '').length > 20 && !String(config.supabaseAnonKey).startsWith('TU_');
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { Accept: 'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message || 'No pudimos conectar con el restaurante.'); return body.data; }
async function direct(path, options = {}) { if (!directEnabled) throw new Error('BFF_UNAVAILABLE'); const response = await fetch(`${config.supabaseUrl}/rest/v1${path}`, { ...options, headers: { Accept: 'application/json', apikey: config.supabaseAnonKey, Authorization: `Bearer ${config.supabaseAnonKey}`, ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || 'Supabase no está disponible.'); return body; }
async function loadDirectData() { const venues = await direct(`/ros_venues?slug=eq.${encodeURIComponent(slug)}&status=eq.active&is_published=eq.true&select=*`); if (!venues[0]) throw new Error('No encontramos este restaurante.'); const venue = venues[0]; const [categories, products] = await Promise.all([direct(`/ros_menu_categories?venue_id=eq.${venue.id}&is_visible=eq.true&order=sort_order.asc`), direct(`/ros_menu_products?venue_id=eq.${venue.id}&is_visible=eq.true&is_available=eq.true&deleted_at=is.null&order=sort_order.asc`)]); return [{ ...venue, is_open: venue.status === 'active' }, { venue, categories: categories.map((c) => ({ ...c, products: products.filter((p) => p.category_id === c.id) })), option_groups: [] }]; }
async function loadData() { if (directEnabled) { try { return await loadDirectData(); } catch (directError) { try { return await Promise.all([api(`/api/v1/public/venues/${slug}`), api(`/api/v1/public/venues/${slug}/menu`)]); } catch { throw directError; } } } return Promise.all([api(`/api/v1/public/venues/${slug}`), api(`/api/v1/public/venues/${slug}/menu`)]); }
const readCart = () => { try { return JSON.parse(localStorage.getItem(`ros_cart_${slug}`) || '[]'); } catch { return []; } };
const imageOf = (item) => item?.image_url || item?.image || item?.photo_url || item?.cover_url || '';
const initials = (name = '') => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();
function ProductImage({ item, category }) { const [failed, setFailed] = useState(false); const src = imageOf(item); return src && !failed ? <img className="food-image" src={src} alt="" loading="lazy" onError={() => setFailed(true)} /> : <div className="food-image-placeholder" aria-hidden="true"><span>{initials(item?.name || category)}</span></div>; }

export default function App() {
  const [venue, setVenue] = useState(null); const [menu, setMenu] = useState(null); const [query, setQuery] = useState(''); const [category, setCategory] = useState('all'); const [cart, setCart] = useState(readCart); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [checkout, setCheckout] = useState(false); const [submitted, setSubmitted] = useState(null); const [submitting, setSubmitting] = useState(false); const [sidebarOpen, setSidebarOpen] = useState(false);
  const load = () => { setLoading(true); setError(''); loadData().then(([v, m]) => { setVenue(v); setMenu(m); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []); useEffect(() => localStorage.setItem(`ros_cart_${slug}`, JSON.stringify(cart)), [cart]);
  const categories = menu?.categories || []; const products = useMemo(() => categories.flatMap((c) => (c.products || []).map((p) => ({ ...p, category: c.name, categoryId: c.id }))).filter((p) => (category === 'all' || String(p.categoryId) === String(category)) && `${p.name} ${p.description || ''}`.toLowerCase().includes(query.toLowerCase().trim())), [categories, category, query]);
  const totalItems = cart.reduce((n, i) => n + i.qty, 0); const total = cart.reduce((n, i) => n + Number(i.unit_price_minor || i.price_minor || 0) * i.qty, 0);
  const add = (p) => setCart((items) => { const unit = p.promo_price_minor && p.promo_price_minor < p.price_minor ? p.promo_price_minor : p.price_minor; const found = items.find((i) => i.id === p.id); return found ? items.map((i) => i.id === p.id ? { ...i, qty: i.qty + 1 } : i) : [...items, { ...p, unit_price_minor: unit, qty: 1 }]; });
  const changeQty = (id, delta) => setCart((items) => items.map((i) => i.id === id ? { ...i, qty: i.qty + delta } : i).filter((i) => i.qty > 0));
  const submitOrder = async (event) => { event.preventDefault(); if (!localStorage.getItem('ros_customer_access_token')) { location.href = `/login.html?role=customer&return=${encodeURIComponent(`${location.pathname}${location.search}`)}`; return; } setSubmitting(true); setError(''); try { const form = new FormData(event.currentTarget); const method = String(form.get('method')); const operationCode = String(form.get('operation_code') || '').trim(); if ((method === 'yape' || method === 'plin') && !operationCode) throw new Error('Ingresa el código de operación de tu pago.'); const body = { customer: { name: form.get('name'), phone: form.get('phone'), email: form.get('email') || null }, fulfillment: { type: 'pickup' }, notes: String(form.get('notes') || ''), items: cart.map((i) => ({ product_id: i.id, quantity: i.qty, option_ids: [] })), idempotency_key: crypto.randomUUID() }; let order; try { order = await api(`/api/v1/public/venues/${slug}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); } catch (e) { if (!directEnabled) throw e; const result = await direct('/rpc/ros_create_public_order', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ p_slug: slug, p_payload: body }) }); order = Array.isArray(result) ? result[0] : result; } if (method === 'yape' || method === 'plin') { const result = await api(`/api/v1/public/venues/${slug}/orders/${order.public_token}/pay`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ payment_method: method, operation_code: operationCode }) }); order = { ...order, payment_status: result.payment_status || 'pending_verification' }; } setSubmitted({ ...order, method, operationCode, customerName: form.get('name') }); setCart([]); setCheckout(false); } catch (e) { setError(e.message); } finally { setSubmitting(false); } };
  if (loading) return <main className="loading-screen"><span className="brand-mark">FP</span><p>Preparando la carta…</p></main>; if (error && !menu) return <main className="loading-screen"><span className="brand-mark">FP</span><p className="error-text">{error}</p><button onClick={load}>Intentar nuevamente</button></main>;
  return <main className="foodie-menu-page"><a className="skip-link" href="#menu">Saltar al contenido</a><header className="foodie-header"><button className="mobile-menu-toggle" type="button" aria-label="Abrir menú" onClick={() => setSidebarOpen(!sidebarOpen)}>☰</button><a className="foodie-logo" href="/" aria-label="FoodiPro, inicio"><span className="logo-tile">✦</span><span>Foodi<span>Pro</span></span></a><div className="foodie-search"><span aria-hidden="true">⌕</span><label htmlFor="food-search" className="sr-only">Buscar en la carta</label><input id="food-search" type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar..." /><kbd>⌘ + Space</kbd></div><div className="foodie-header-actions"><button type="button" aria-label="Cambiar tema">☼</button><button type="button" aria-label="Notificaciones">♧</button><a className="header-account" href="/login.html?role=customer">Iniciar sesión</a></div></header>
    <div className={`foodie-layout ${sidebarOpen ? 'sidebar-visible' : ''}`}><aside className="foodie-sidebar" aria-label="Navegación principal"><nav><a className="foodie-nav active" href="#menu" aria-label="Explorar carta">▦</a><button className="foodie-nav" type="button" aria-label="Filtrar carta" onClick={() => document.getElementById('food-search')?.focus()}>☷</button><a className="foodie-nav" href="#menu" aria-label="Favoritos">♡</a><a className="foodie-nav" href="#cart" aria-label="Tu pedido">▢</a><a className="foodie-nav" href="/cliente.html" aria-label="Mi cuenta">◎</a></nav></aside>
      <div className="foodie-content"><section className="menu-intro"><div><p className="foodie-eyebrow">{venue?.city || 'Lima, Perú'} · {venue?.is_open ? 'Abierto ahora' : 'Cerrado'}</p><h1>{venue?.name || 'Explora la carta'}</h1><p className="menu-subtitle">Elige algo delicioso de nuestra carta y disfruta tu pedido.</p></div><span className="venue-status"><i />{venue?.is_open ? 'Disponible para recojo' : 'Cerrado por ahora'}</span></section>
        <section className="category-section" aria-labelledby="categories-title"><div className="foodie-section-heading"><h2 id="categories-title">Explora categorías</h2><button type="button" onClick={() => setCategory('all')}>Ver todo <span>→</span></button></div><div className="category-tiles"><button className={`category-tile ${category === 'all' ? 'selected' : ''}`} onClick={() => setCategory('all')}><span className="category-art category-all">✦</span><strong>Todo</strong></button>{categories.map((c) => <button key={c.id} className={`category-tile ${String(category) === String(c.id) ? 'selected' : ''}`} onClick={() => setCategory(c.id)}><ProductImage item={c.products?.[0]} category={c.name} /><strong>{c.name}</strong></button>)}</div></section>
        <section className="products-section" id="menu" aria-labelledby="products-title"><div className="foodie-section-heading"><div className="menu-tabs"><button className={category === 'all' ? 'tab-active' : ''} onClick={() => setCategory('all')} id="products-title">Populares</button><button onClick={() => setQuery('')}>Recientes</button></div><span className="item-count">{products.length} opciones</span></div><div className="food-product-grid" aria-live="polite">{products.map((p) => { const price = p.promo_price_minor && p.promo_price_minor < p.price_minor ? p.promo_price_minor : p.price_minor; const inCart = cart.some((i) => i.id === p.id); return <article className="food-product-card" key={p.id}><div className="product-image-wrap"><ProductImage item={p} category={p.category} /><button className={`wishlist-button ${inCart ? 'is-added' : ''}`} type="button" aria-label={`${inCart ? 'En tu pedido: ' : 'Agregar '}${p.name}`} onClick={() => add(p)}>{inCart ? '✓' : '+'}</button></div><div className="food-product-info"><h3>{p.name}</h3><p>{p.description || 'Preparado con ingredientes seleccionados.'}</p><div className="food-product-footer"><strong>{money(price)}</strong>{p.promo_price_minor && p.promo_price_minor < p.price_minor && <del>{money(p.price_minor)}</del>}<span className="rating">★ 2.5K+</span></div><button className="order-now" type="button" onClick={() => add(p)}>Order Now <span>→</span></button></div></article>; })}</div>{!products.length && <div className="empty-menu"><span>⌕</span><h3>No encontramos ese plato</h3><p>Prueba con otra búsqueda o categoría.</p></div>}</section>
      </div></div>{error && menu && <p className="inline-error" role="alert">{error}</p>}{cart.length > 0 && <aside className="cart-dock" id="cart" aria-label="Resumen de tu pedido"><div className="cart-summary"><span className="cart-badge">{totalItems}</span><div><strong>Tu pedido</strong><small>{totalItems} {totalItems === 1 ? 'producto' : 'productos'}</small></div><strong className="cart-total">{money(total)}</strong></div><button className="cart-cta" onClick={() => setCheckout(true)}>Revisar pedido <span>→</span></button></aside>}
    {submitted && <section className="customer-dashboard" aria-labelledby="order-dashboard-title"><div className="dashboard-head"><div><p className="eyebrow">Panel de tu pedido</p><h2 id="order-dashboard-title">¡Listo, {submitted.customerName}!</h2></div><span className="status-chip">En revisión</span></div><div className="order-code"><span>Código de seguimiento</span><strong>{submitted.public_token || 'Registrado'}</strong></div><p className="dashboard-note">Registramos tu pedido. El local validará el pago antes de prepararlo.</p><button className="text-button" onClick={() => setSubmitted(null)}>Volver a la carta</button></section>}
    {checkout && <div className="modal-backdrop"><section className="checkout-panel" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><button className="close-button" onClick={() => setCheckout(false)} aria-label="Cerrar">×</button><p className="eyebrow">Último paso</p><h2 id="checkout-title">Confirma tu pedido</h2><div className="checkout-items">{cart.map((i) => <div className="checkout-item" key={i.id}><span>{i.qty} × {i.name}</span><span>{money(i.unit_price_minor * i.qty)}</span><div className="qty-controls"><button type="button" onClick={() => changeQty(i.id, -1)} aria-label={`Quitar ${i.name}`}>−</button><span>{i.qty}</span><button type="button" onClick={() => changeQty(i.id, 1)} aria-label={`Agregar ${i.name}`}>+</button></div></div>)}</div><form onSubmit={submitOrder}><div className="form-grid"><label>Nombre completo<input name="name" required autoComplete="name" placeholder="¿Cómo te llamamos?" /></label><label>Celular<input name="phone" required inputMode="tel" autoComplete="tel" placeholder="987 654 321" /></label></div><label>Correo <em>(opcional)</em><input name="email" type="email" autoComplete="email" placeholder="tu@correo.com" /></label><label>Forma de pago<select name="method" defaultValue="yape"><option value="yape">Yape</option><option value="plin">Plin</option><option value="cash">Efectivo al recoger</option></select></label><label>Código de operación <em>(requerido para Yape o Plin)</em><input name="operation_code" inputMode="numeric" placeholder="Código de tu comprobante" /></label><label>Nota para el local <em>(opcional)</em><textarea name="notes" rows="2" placeholder="Ej. sin cebolla…" /></label><div className="checkout-total"><span>Total estimado</span><strong>{money(total)}</strong></div><button className="submit-button" type="submit" disabled={submitting}>{submitting ? 'Enviando…' : 'Enviar pedido'} <span>→</span></button></form></section></div>}
  </main>;
}
