import { useEffect, useMemo, useState } from 'react';

const slug = import.meta.env.VITE_VENUE_SLUG || 'casa-aurora';
const workspaceSection = new URLSearchParams(location.search).get('section') || 'carta';
const money = (minor = 0) => new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN', minimumFractionDigits: 2 }).format(Number(minor || 0) / 100).replace('PEN', 'S/');
const config = window.__ROS_CONFIG__ || {};
const directEnabled = /^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(String(config.supabaseUrl || '')) && String(config.supabaseAnonKey || '').length > 20 && !String(config.supabaseAnonKey).startsWith('TU_');
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { Accept: 'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message || 'No pudimos conectar con el restaurante.'); return body.data; }
async function direct(path, options = {}) { if (!directEnabled) throw new Error('BFF_UNAVAILABLE'); const response = await fetch(`${config.supabaseUrl}/rest/v1${path}`, { ...options, headers: { Accept: 'application/json', apikey: config.supabaseAnonKey, Authorization: `Bearer ${config.supabaseAnonKey}`, ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || 'Supabase no está disponible.'); return body; }
async function loadDirectData() { const venues = await direct(`/ros_venues?slug=eq.${encodeURIComponent(slug)}&status=eq.active&is_published=eq.true&select=*`); if (!venues[0]) throw new Error('No encontramos este restaurante.'); const venue = venues[0]; const [categories, products] = await Promise.all([direct(`/ros_menu_categories?venue_id=eq.${venue.id}&is_visible=eq.true&order=sort_order.asc`), direct(`/ros_menu_products?venue_id=eq.${venue.id}&is_visible=eq.true&is_available=eq.true&deleted_at=is.null&order=sort_order.asc`)]); return [{ ...venue, is_open: venue.status === 'active' }, { venue, categories: categories.map((c) => ({ ...c, products: products.filter((p) => p.category_id === c.id) })), option_groups: [] }]; }
async function loadData() { if (directEnabled) { try { return await loadDirectData(); } catch (directError) { try { return await Promise.all([api(`/api/v1/public/venues/${slug}`), api(`/api/v1/public/venues/${slug}/menu`)]); } catch { throw directError; } } } return Promise.all([api(`/api/v1/public/venues/${slug}`), api(`/api/v1/public/venues/${slug}/menu`)]); }
const readCart = () => { try { return JSON.parse(localStorage.getItem(`ros_cart_${slug}`) || '[]'); } catch { return []; } };
const imageOf = (item) => item?.image_url || item?.image || item?.photo_url || item?.cover_url || '';
const initials = (name = '') => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();
function ProductImage({ item, category }) { const [failed, setFailed] = useState(false); const src = imageOf(item); return src && !failed ? <img className="food-image" src={src} alt="" loading="lazy" onError={() => setFailed(true)} /> : <div className="food-image-placeholder" aria-hidden="true"><span>{initials(item?.name || category)}</span></div>; }
const generatedCategoryImage = '/assets/generated/category-foods.png';
const generatedProductImage = '/assets/generated/menu-products.png';
function GeneratedFoodImage({ src, index = 0, columns = 3, rows = 3, className = '' }) { const column = index % columns; const row = Math.floor(index / columns); return <span className={`generated-food-image ${className}`} style={{ '--food-sheet': `url(${src})`, '--food-x': `${columns > 1 ? column * (100 / (columns - 1)) : 0}%`, '--food-y': `${rows > 1 ? row * (100 / (rows - 1)) : 0}%`, '--food-size-x': `${columns * 100}%`, '--food-size-y': `${rows * 100}%` }} aria-hidden="true" />; }
const moduleLabels = { explore: 'Explorar carta', filter: 'Filtrar carta', favorites: 'Favoritos', cart: 'Tu pedido', account: 'Mi cuenta' };
function InicioDashboard({ venue, categories, cart, totalItems, total, setCheckout }) { const products = categories.flatMap((c) => (c.products || []).map((p) => ({ ...p, category: c.name }))).slice(0, 3); return <div className="inicio-dashboard"><section className="inicio-hero" aria-labelledby="inicio-title"><div className="inicio-hero-copy"><p className="foodie-eyebrow">{venue?.name || 'FoodiPro'} · Inicio</p><h1 id="inicio-title">Tu próximo antojo<br /><em>empieza aquí.</em></h1><p>Descubre lo mejor de la carta, revisa tus pedidos y disfruta cada momento.</p><a className="inicio-primary" href="#inicio-category">Explorar categorías <span>→</span></a></div><img src="/assets/generated/menu-promo.png" alt="Hamburguesa gourmet" /></section><section className="inicio-section" id="inicio-category" aria-labelledby="inicio-category-title"><div className="inicio-heading"><h2 id="inicio-category-title">Categoría</h2><a href="?section=carta">Ver todo <span>→</span></a></div><div className="inicio-category-grid">{categories.slice(0, 3).map((c, index) => <a className="inicio-category-card" href="?section=carta" key={c.id}><span>{c.name}</span><GeneratedFoodImage src={generatedCategoryImage} index={index} /></a>)}</div></section><section className="inicio-section inicio-recent" aria-labelledby="inicio-recent-title"><div className="inicio-heading"><h2 id="inicio-recent-title">Recent Order</h2><a href="#cart">Ver todo <span>→</span></a></div><div className="inicio-recent-grid">{products.map((product, index) => <article className="inicio-recent-card" key={product.id}><div className="inicio-meta">Disponible ahora · {product.category}</div><h3>{product.name}</h3><strong>{money(product.promo_price_minor && product.promo_price_minor < product.price_minor ? product.promo_price_minor : product.price_minor)}</strong><GeneratedFoodImage src="/assets/generated/recent-dishes.png" index={index} columns={3} rows={1} /></article>)}{!products.length && <div className="inicio-empty">Todavía no hay productos disponibles en la carta.</div>}</div></section><button className="inicio-cart-shortcut" type="button" onClick={() => setCheckout(true)} disabled={!cart.length}><span>{totalItems ? `${totalItems} producto${totalItems === 1 ? '' : 's'}` : 'Tu pedido está vacío'}</span><strong>{totalItems ? money(total) : 'Explorar carta'} <b>→</b></strong></button></div>; }

export default function App() {
  const [venue, setVenue] = useState(null); const [menu, setMenu] = useState(null); const [query, setQuery] = useState(''); const [category, setCategory] = useState('all'); const [cart, setCart] = useState(readCart); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [checkout, setCheckout] = useState(false); const [submitted, setSubmitted] = useState(null); const [submitting, setSubmitting] = useState(false); const [sidebarOpen, setSidebarOpen] = useState(false);
  const load = () => { setLoading(true); setError(''); loadData().then(([v, m]) => { setVenue(v); setMenu(m); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []); useEffect(() => localStorage.setItem(`ros_cart_${slug}`, JSON.stringify(cart)), [cart]);
  const categories = menu?.categories || []; const products = useMemo(() => categories.flatMap((c) => (c.products || []).map((p) => ({ ...p, category: c.name, categoryId: c.id }))).filter((p) => (category === 'all' || String(p.categoryId) === String(category)) && `${p.name} ${p.description || ''}`.toLowerCase().includes(query.toLowerCase().trim())), [categories, category, query]);
  const totalItems = cart.reduce((n, i) => n + i.qty, 0); const total = cart.reduce((n, i) => n + Number(i.unit_price_minor || i.price_minor || 0) * i.qty, 0);
  const add = (p) => setCart((items) => { const unit = p.promo_price_minor && p.promo_price_minor < p.price_minor ? p.promo_price_minor : p.price_minor; const found = items.find((i) => i.id === p.id); return found ? items.map((i) => i.id === p.id ? { ...i, qty: i.qty + 1 } : i) : [...items, { ...p, unit_price_minor: unit, qty: 1 }]; });
  const changeQty = (id, delta) => setCart((items) => items.map((i) => i.id === id ? { ...i, qty: i.qty + delta } : i).filter((i) => i.qty > 0));
  const submitOrder = async (event) => { event.preventDefault(); if (!localStorage.getItem('ros_customer_access_token')) { location.href = `/login.html?role=customer&return=${encodeURIComponent(`${location.pathname}${location.search}`)}`; return; } setSubmitting(true); setError(''); try { const form = new FormData(event.currentTarget); const method = String(form.get('method')); const operationCode = String(form.get('operation_code') || '').trim(); if ((method === 'yape' || method === 'plin') && !operationCode) throw new Error('Ingresa el código de operación de tu pago.'); const body = { customer: { name: form.get('name'), phone: form.get('phone'), email: form.get('email') || null }, fulfillment: { type: 'pickup' }, notes: String(form.get('notes') || ''), items: cart.map((i) => ({ product_id: i.id, quantity: i.qty, option_ids: [] })), idempotency_key: crypto.randomUUID() }; let order; try { order = await api(`/api/v1/public/venues/${slug}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); } catch (e) { if (!directEnabled) throw e; const result = await direct('/rpc/ros_create_public_order', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ p_slug: slug, p_payload: body }) }); order = Array.isArray(result) ? result[0] : result; } if (method === 'yape' || method === 'plin') { const result = await api(`/api/v1/public/venues/${slug}/orders/${order.public_token}/pay`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ payment_method: method, operation_code: operationCode }) }); order = { ...order, payment_status: result.payment_status || 'pending_verification' }; } setSubmitted({ ...order, method, operationCode, customerName: form.get('name') }); setCart([]); setCheckout(false); } catch (e) { setError(e.message); } finally { setSubmitting(false); } };
  if (loading) return <main className="loading-screen"><span className="brand-mark">FP</span><p>Preparando la carta…</p></main>; if (error && !menu) return <main className="loading-screen"><span className="brand-mark">FP</span><p className="error-text">{error}</p><button onClick={load}>Intentar nuevamente</button></main>;
  return <main className={`foodie-menu-page workspace-page-${workspaceSection}`}><a className="skip-link" href="#menu">Saltar al contenido</a><header className="foodie-header"><button className="mobile-menu-toggle" type="button" aria-label="Abrir menú" onClick={() => setSidebarOpen(!sidebarOpen)}>☰</button><a className="foodie-logo" href="/" aria-label="FoodiPro, inicio"><span className="logo-tile">✦</span><span>Foodi<span>Pro</span></span></a><div className="foodie-search"><span aria-hidden="true">⌕</span><label htmlFor="food-search" className="sr-only">Buscar en la carta</label><input id="food-search" type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar..." /><kbd>⌘ + Space</kbd></div><div className="foodie-header-actions"><button type="button" aria-label="Cambiar tema">☼</button><button type="button" aria-label="Notificaciones">♧</button><a className="header-account" href="/cliente.html">Mi espacio</a></div></header>
    <div className={`foodie-layout ${sidebarOpen ? 'sidebar-visible' : ''}`}><aside className="foodie-sidebar" aria-label="Navegación principal"><nav><div className="foodie-sidebar-group"><a className="foodie-nav active" href="#menu" aria-label={moduleLabels.explore} title={moduleLabels.explore} data-label={moduleLabels.explore}>▦<span>{moduleLabels.explore}</span></a><button className="foodie-nav" type="button" aria-label={moduleLabels.filter} title={moduleLabels.filter} data-label={moduleLabels.filter} onClick={() => document.getElementById('food-search')?.focus()}>☷<span>{moduleLabels.filter}</span></button><a className="foodie-nav" href="#menu" aria-label={moduleLabels.favorites} title={moduleLabels.favorites} data-label={moduleLabels.favorites}>♡<span>{moduleLabels.favorites}</span></a></div><div className="foodie-sidebar-group foodie-sidebar-secondary"><a className="foodie-nav" href="#cart" aria-label={moduleLabels.cart} title={moduleLabels.cart} data-label={moduleLabels.cart}>▢<span>{moduleLabels.cart}</span></a><a className="foodie-nav" href="/cliente.html" aria-label={moduleLabels.account} title={moduleLabels.account} data-label={moduleLabels.account}>◎<span>{moduleLabels.account}</span></a></div></nav></aside>
      <div className={`foodie-content workspace-section-${workspaceSection}`}>{workspaceSection === 'inicio' && <InicioDashboard venue={venue} categories={categories} cart={cart} totalItems={totalItems} total={total} setCheckout={setCheckout} />}<section className="customer-workspace-banner" aria-labelledby="workspace-title"><div className="workspace-copy"><p className="foodie-eyebrow">FoodiPro · Tu espacio</p><h1 id="workspace-title">Vive para comer.<br /><em>Disfruta cada momento.</em></h1><p>Explora la carta, revisa tus pedidos y arma tu próximo antojo en un solo lugar.</p><div className="workspace-actions"><a className="workspace-primary" href="#menu">Explorar la carta <span>→</span></a><a className="workspace-secondary" href="/cliente.html#orders">Mis pedidos</a></div></div><img src="/foodipro-customer-reference.webp" alt="" className="workspace-art" /></section><section className="menu-intro"><div><p className="foodie-eyebrow">{venue?.city || 'Lima, Perú'} · {venue?.is_open ? 'Abierto ahora' : 'Cerrado'}</p><h2>{venue?.name || 'Explora la carta'}</h2><p className="menu-subtitle">Módulo carta · Elige algo delicioso y disfruta tu pedido.</p></div><span className="venue-status"><i />{venue?.is_open ? 'Disponible para recojo' : 'Cerrado por ahora'}</span></section>
        <a className="inicio-module-link" href={`?venue=${slug}&section=inicio`} aria-label="Abrir módulo Inicio">Inicio <span>⌂</span></a>{workspaceSection === 'promociones' && <section className="carta-promo" aria-labelledby="promo-title"><div><p className="foodie-eyebrow">Promoción de temporada</p><h2 id="promo-title">Un antojo especial para hoy</h2><p>Descubre las novedades del menú de {venue?.name || 'tu restaurante'}.</p></div><img src="/assets/generated/menu-promo.png" alt="Hamburguesa gourmet en promoción" /></section>}
        <section className="category-section" aria-labelledby="categories-title"><div className="foodie-section-heading"><h2 id="categories-title">Explora categorías</h2><button type="button" onClick={() => setCategory('all')}>Ver todo <span>→</span></button></div><div className="category-tiles"><button className={`category-tile ${category === 'all' ? 'selected' : ''}`} onClick={() => setCategory('all')}><span className="category-art category-all">✦</span><strong>Todo</strong></button>{categories.map((c, index) => <button key={c.id} className={`category-tile ${String(category) === String(c.id) ? 'selected' : ''}`} onClick={() => setCategory(c.id)}><ProductImage item={c.products?.[0]} category={c.name} /><GeneratedFoodImage src={generatedCategoryImage} index={index} className="category-generated" /><strong>{c.name}</strong></button>)}</div></section>
        <section className="products-section" id="menu" aria-labelledby="products-title"><div className="foodie-section-heading"><div className="menu-tabs"><button className={category === 'all' ? 'tab-active' : ''} onClick={() => setCategory('all')} id="products-title">Popular</button><button onClick={() => setQuery('')}>Recent</button></div><span className="item-count">{products.length} opciones</span></div><div className="food-product-grid" aria-live="polite">{products.map((p, index) => { const price = p.promo_price_minor && p.promo_price_minor < p.price_minor ? p.promo_price_minor : p.price_minor; const inCart = cart.some((i) => i.id === p.id); return <article className="food-product-card" key={p.id}><div className="product-image-wrap"><ProductImage item={p} category={p.category} /><GeneratedFoodImage src={generatedProductImage} index={index} columns={2} rows={3} className="product-generated" /><button className={`wishlist-button ${inCart ? 'is-added' : ''}`} type="button" aria-label={`${inCart ? 'En tu pedido: ' : 'Agregar '}${p.name}`} onClick={() => add(p)}>{inCart ? '✓' : '♡'}</button></div><div className="food-product-info"><h3>{p.name}</h3><p>{p.description || 'Preparado con ingredientes seleccionados.'}</p><div className="food-product-footer"><strong>{money(price)}</strong>{p.promo_price_minor && p.promo_price_minor < p.price_minor && <del>{money(p.price_minor)}</del>}<span className="rating">★ 2.5K+</span></div><div className="product-actions"><button className="wishlist-action" type="button" onClick={() => add(p)}>♡ <span>Wishlist</span></button><button className="order-now" type="button" onClick={() => add(p)}>Order Now</button></div></div></article>; })}</div>{!products.length && <div className="empty-menu"><span>⌕</span><h3>No encontramos ese plato</h3><p>Prueba con otra búsqueda o categoría.</p></div>}</section></div>
        <aside className="foodie-right-rail" aria-label="Resumen del restaurante y tu pedido">
          <section className="right-rail-card venue-card">
            <div className="right-rail-heading"><div><p className="foodie-eyebrow">Tu restaurante</p><h2>{venue?.name || 'Casa Aurora'}</h2></div><span className="right-rail-dot" aria-hidden="true" /></div>
            <div className="venue-visual"><span>{initials(venue?.name || 'Casa Aurora')}</span><small>{venue?.is_open ? 'Abierto ahora' : 'Cerrado por ahora'}</small></div>
            <div className="venue-facts"><div><span>Ubicación</span><strong>{venue?.address || venue?.city || 'Lima, Perú'}</strong></div><div><span>Disponibilidad</span><strong>{venue?.is_open ? 'Recojo disponible' : 'Consulta al local'}</strong></div></div>
            <p className="right-rail-note">Explora la carta y arma tu pedido con los productos disponibles del local.</p>
            <a className="right-rail-outline" href="#menu">Ver la carta <span>→</span></a>
          </section>
          <section className="right-rail-card order-card" id="cart">
            <div className="right-rail-heading"><div><p className="foodie-eyebrow">Resumen</p><h2>Tu pedido</h2></div><span className="order-count">{totalItems}</span></div>
            {cart.length ? <><div className="right-order-items">{cart.slice(0, 3).map((item) => <div className="right-order-item" key={item.id}><span className="right-order-thumb">{initials(item.name)}</span><div><strong>{item.name}</strong><small>{item.qty} × {money(item.unit_price_minor)}</small></div><b>{money(item.unit_price_minor * item.qty)}</b></div>)}</div>{cart.length > 3 && <p className="right-rail-note">+ {cart.length - 3} productos más en tu pedido</p>}<div className="right-order-total"><span>Total estimado</span><strong>{money(total)}</strong></div><button className="right-rail-cta" type="button" onClick={() => setCheckout(true)}>Revisar pedido <span>→</span></button></> : <div className="right-empty"><span>＋</span><p>Aún no agregas productos.</p><small>Elige algo de la carta para comenzar.</small><a href="#menu">Explorar opciones</a></div>}
          </section>
        </aside>
      </div>{error && menu && <p className="inline-error" role="alert">{error}</p>}{cart.length > 0 && <aside className="cart-dock" id="cart-dock" aria-label="Resumen de tu pedido"><div className="cart-summary"><span className="cart-badge">{totalItems}</span><div><strong>Tu pedido</strong><small>{totalItems} {totalItems === 1 ? 'producto' : 'productos'}</small></div><strong className="cart-total">{money(total)}</strong></div><button className="cart-cta" onClick={() => setCheckout(true)}>Revisar pedido <span>→</span></button></aside>}
    {submitted && <section className="customer-dashboard" aria-labelledby="order-dashboard-title"><div className="dashboard-head"><div><p className="eyebrow">Panel de tu pedido</p><h2 id="order-dashboard-title">¡Listo, {submitted.customerName}!</h2></div><span className="status-chip">En revisión</span></div><div className="order-code"><span>Código de seguimiento</span><strong>{submitted.public_token || 'Registrado'}</strong></div><p className="dashboard-note">Registramos tu pedido. El local validará el pago antes de prepararlo.</p><button className="text-button" onClick={() => setSubmitted(null)}>Volver a la carta</button></section>}
    {checkout && <div className="modal-backdrop"><section className="checkout-panel" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><button className="close-button" onClick={() => setCheckout(false)} aria-label="Cerrar">×</button><p className="eyebrow">Último paso</p><h2 id="checkout-title">Confirma tu pedido</h2><div className="checkout-items">{cart.map((i) => <div className="checkout-item" key={i.id}><span>{i.qty} × {i.name}</span><span>{money(i.unit_price_minor * i.qty)}</span><div className="qty-controls"><button type="button" onClick={() => changeQty(i.id, -1)} aria-label={`Quitar ${i.name}`}>−</button><span>{i.qty}</span><button type="button" onClick={() => changeQty(i.id, 1)} aria-label={`Agregar ${i.name}`}>+</button></div></div>)}</div><form onSubmit={submitOrder}><div className="form-grid"><label>Nombre completo<input name="name" required autoComplete="name" placeholder="¿Cómo te llamamos?" /></label><label>Celular<input name="phone" required inputMode="tel" autoComplete="tel" placeholder="987 654 321" /></label></div><label>Correo <em>(opcional)</em><input name="email" type="email" autoComplete="email" placeholder="tu@correo.com" /></label><label>Forma de pago<select name="method" defaultValue="yape"><option value="yape">Yape</option><option value="plin">Plin</option><option value="cash">Efectivo al recoger</option></select></label><label>Código de operación <em>(requerido para Yape o Plin)</em><input name="operation_code" inputMode="numeric" placeholder="Código de tu comprobante" /></label><label>Nota para el local <em>(opcional)</em><textarea name="notes" rows="2" placeholder="Ej. sin cebolla…" /></label><div className="checkout-total"><span>Total estimado</span><strong>{money(total)}</strong></div><button className="submit-button" type="submit" disabled={submitting}>{submitting ? 'Enviando…' : 'Enviar pedido'} <span>→</span></button></form></section></div>}
  </main>;
}
